### ISSUE TITLE
[bug] VDP registers view window is illegible on Mac OS-X 10.13

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/debugger#67] opened 2018-09-30 14:55 UTC
As the attached screenshot shows, the VDP registers window has become illegible on Mac OS-X 10.13.

Tested with openMSX-debugger v0.10.0-263-g1ce3e28 on Mac OS-X 10.13.6.
<img width="790" alt="screen shot 2018-09-30 at 11 51 49" src="https://user-images.githubusercontent.com/13080763/46258894-c0eadc80-c4a7-11e8-8db7-42d1a8e9189e.png">

**Comment by MBilderbeek** [comment] 2018-09-30 14:57
Can you try the latest build of this place: http://openmsx.fixato.net/builds/mac/debugger/ ?

**Comment by MBilderbeek** [comment] 2018-09-30 15:05
This is what it looks like on my Linux box:
![screenshot from 2018-09-30 17-02-08](https://user-images.githubusercontent.com/12675978/46258971-99f5d000-c4d2-11e8-8eae-336f58663eed.png)

Not sure what to do if this is Mac specific. Perhaps @niekvlessert can check on his Mac?

**Comment by sdsnatcher** [comment] 2018-09-30 15:32
The latest build there is the 263-g1ce3e28 I just tested.

**Comment by MBilderbeek** [comment] 2018-09-30 16:42
Oh, indeed, sorry :) I can't really help here, as you can see it looks fine on Linux and I don't have a Mac to test/develop with. What caused the change? Update of macOS?

**Comment by MBilderbeek** [comment] 2018-09-30 16:42
What if you update your Qt5 install, using brew?

**Comment by edwin-v** [comment] 2018-09-30 19:52
Why is the screenshot so pixel-y? Does Qt not handle 4k on Mac?

**Comment by sdsnatcher** [comment] 2018-10-02 23:41
> what if you update your Qt5 install, using brew?


I'll try this in some days. Right now my landline connection is broken, so I can only access via tethering on the smartphone. There's no way to make big downloads with that.

> Why is the screenshot so pixel-y? Does Qt not handle 4k on Mac?

I have no idea.

**Comment by sdsnatcher** [comment] 2018-10-04 21:13
Ok, I updated Qt to the latest version available on brew (qt-5.11.2.high_sierra.bottle.tar.gz). The problem persists.

**Comment by MBilderbeek** [comment] 2018-10-04 21:31
Too bad! I have no idea how I can help you though... I hope someone else can. Perhaps @niekvlessert can try on his Mac or so...

**Comment by edwin-v** [comment] 2018-10-07 10:05
It may be useful to try and figure out why it renders pixelated. Looks like something isn't scaling properly and that may be the cause of the buttons scaling incorrectly.

**Comment by niekvlessert** [comment] 2018-10-11 13:11
<img width="1018" alt="screen shot 2018-10-11 at 15 08 36" src="https://user-images.githubusercontent.com/1013068/46806334-98949500-cd67-11e8-88d3-e503e2311ba6.png">

I have the issue too, 10.13.6. My mac is 5k. Used qt5.

**Comment by MBilderbeek** [comment] 2021-10-31 13:29
I think this has been fixed with 89f17f88e6b978e0d6140561f7e7655a7501bd55. Please confirm.

**Closed by MBilderbeek** 2021-10-31 13:29 UTC

**Comment by sdsnatcher** [comment] 2021-10-31 15:45
The newest build of the debugger for macOS seems to be from 2020-12-28 21:50, so I won't be able to test and confirm if this bug was solved.

https://openmsx.fixato.net/builds/mac/debugger/

**Comment by MBilderbeek** [comment] 2021-10-31 15:51
@niekvlessert Can you update that build?

**Comment by sdsnatcher** [comment] 2021-10-31 22:35
Isn't it possible to have automatic builds of the debugger there, just like it happens with openMSX?
