### ISSUE TITLE
Unable to attach two instances of the debugger to two different openMSX processes

### ISSUE THREAD

**Issue by mcolom** [openMSX/debugger#120] opened 2022-05-19 16:43 UTC
Before it was possible to launch two different instances of the debugger and attach each of them to a different openMSX process.
However, now the second instance of the debugger is unable to attach is the first one is already attached. The Connect button does nothing in this case.

A git bisect indicates that the problem first appears at commit 2c3fd4cf5d16680e142f308b84dcd558c2c0a95f. Indeed, the previous one (ca365c2d1f1d0237c5e2b03765bf1c45b2be4f9d) doesn't have the problem.

Tested on Debian bookworm/sid.

**Comment by m9710797** [comment] 2022-05-19 16:56
Thanks for reporting.

Actually my patch broke several other things as well. I already discussed it with David, and he'll fix it in the near future.

The problem is that the (old) slot annotations are still needed for the connections that are created (via string lookup) in the .ui files.

**Comment by mcolom** [comment] 2022-05-19 17:02
Anyway, I guess this "double attach" thing I'm doing is not the typical use, and it's easy to checkout to the previous commit if needed. Thanks Wouter and everyone for your amazing work! :)

**Comment by m9710797** [comment] 2022-05-21 07:36
Should be fixed in the latest revision.

**Closed by m9710797** 2022-05-21 07:36 UTC
